//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Provider { get; set; }
        public int Image { get; set; }
        public decimal Price { get; set; }
        public int EachPackAmount { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
